### ISSUE TITLE
example_fast_api:  libjxl.so.0.7: cannot open shared object file: No such file or directory; KeyError: 'format_name'

### ISSUE THREAD

**Issue by espeed** [KoljaB/RealtimeTTS#145]
Server ready
INFO:     Started server process [3479353]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Synthesizing: "Hello World"
INFO:     127.0.0.1:36486 - "GET /tts?text=Hello%20World HTTP/1.1" 200 OK
ffmpeg: error while loading shared libraries: libjxl.so.0.7: cannot open shared object file: No such file or directory
ffprobe: error while loading shared libraries: libjxl.so.0.7: cannot open shared object file: No such file or directory
ffprobe: error while loading shared libraries: libjxl.so.0.7: cannot open shared object file: No such file or directory
WARNING:root:engine system failed to synthesize sentence "Hello World" with error: 'format_name'
Traceback: Traceback (most recent call last):
  File "/home/james/.local/lib/python3.12/site-packages/RealtimeTTS/text_to_stream.py", line 377, in synthesize_worker
    success = self.engine.synthesize(sentence)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/lib/python3.12/site-packages/RealtimeTTS/engines/system_engine.py", line 75, in synthesize
    if info['format_name'] == 'aiff':
       ~~~~^^^^^^^^^^^^^^^
KeyError: 'format_name'

Error: 'format_name'
WARNING:root:engine system is the only engine available, can't switch to another engine

**Comment by espeed** [comment]
Linking to older versions libjxl gets the demo to play a sound...

sudo ln -s libjxl.so.0.8 libjxl.so.0.7
sudo ln -s libjxl_threads.so.0.8 libjxl_threads.so.0.7

However, it only plays once. When pressing "speak" subsequent times, no sound.

**Comment by KoljaB** [comment]
Could you please activate debug logging on the server and post the full logging, maybe then I can see what's going on.

**Comment by espeed** [comment]
.... second play attempt (full server debug log attached)...
INFO:root:stream stop
DEBUG:root:Terminating stream
INFO:     192.168.3.116:51906 - "GET /favicon.ico HTTP/1.0" 200 OK
DEBUG:root:Playing audio for text: This is a text to speech demo text
Synthesizing: "This is a text to speech demo text"
DEBUG:root:Currently speaking: This is a text to speech demo text
INFO:root:stream start
DEBUG:root:Muted mode, no opening stream
INFO:root:Time to split sentences: 8.58306884765625e-05
INFO:root:Time to split sentences: 4.458427429199219e-05
INFO:root:Time to split sentences: 3.981590270996094e-05
INFO:root:Time to split sentences: 3.695487976074219e-05
INFO:root:Time to split sentences: 5.316734313964844e-05
INFO:root:Time to split sentences: 3.719329833984375e-05
INFO:root:Time to split sentences: 3.552436828613281e-05
INFO:root:Time to split sentences: 4.00543212890625e-05
INFO:root:Time to split sentences: 4.267692565917969e-05
INFO:root:Time to split sentences: 3.5762786865234375e-05
INFO:root:Time to split sentences: 3.552436828613281e-05
INFO:root:Time to split sentences: 3.5762786865234375e-05
INFO:root:Time to split sentences: 3.838539123535156e-05
INFO:     192.168.3.116:60724 - "GET /tts?text=This%20is%20a%20text%20to%20speech%20demo%20text HTTP/1.0" 200 OK


[server-debug-output.txt](https://github.com/user-attachments/files/17283214/server-debug-output.txt)
