### ISSUE TITLE
我在执行test的时候报错ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。

### ISSUE THREAD

**Issue by 120805481** [KoljaB/RealtimeTTS#233]
D:\ProgramData\anaconda3\envs\RealtimeTTS2\python.exe D:\BaiduNetdiskDownload\RealtimeTTS\tests\coqui_test.py 
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\utils\import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 58, in <module>
    from ...modeling_flash_attention_utils import _flash_attention_forward
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\modeling_flash_attention_utils.py", line 27, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\RealtimeTTS\tests\coqui_test.py", line 2, in <module>
    from RealtimeTTS import TextToAudioStream, CoquiEngine
  File "D:\BaiduNetdiskDownload\RealtimeTTS\RealtimeTTS\__init__.py", line 1, in <module>
    from .text_to_stream import TextToAudioStream  # noqa: F401
  File "D:\BaiduNetdiskDownload\RealtimeTTS\RealtimeTTS\text_to_stream.py", line 4, in <module>
    from .engines import BaseEngine
  File "D:\BaiduNetdiskDownload\RealtimeTTS\RealtimeTTS\engines\__init__.py", line 24, in <module>
    from TTS.utils.manage import ModelManager
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\TTS\__init__.py", line 16, in <module>
    from TTS.tts.configs.xtts_config import XttsConfig
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\TTS\tts\configs\xtts_config.py", line 5, in <module>
    from TTS.tts.models.xtts import XttsArgs, XttsAudioConfig
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\TTS\tts\models\xtts.py", line 13, in <module>
    from TTS.tts.layers.xtts.gpt import GPT
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 10, in <module>
    from TTS.tts.layers.tortoise.autoregressive import (
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\TTS\tts\layers\tortoise\autoregressive.py", line 11, in <module>
    from transformers import GPT2Config, GPT2PreTrainedModel, LogitsProcessorList
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\utils\import_utils.py", line 1767, in __getattr__
    value = getattr(module, name)
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\utils\import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ProgramData\anaconda3\envs\RealtimeTTS2\lib\site-packages\transformers\utils\import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。

Process finished with exit code 1   这个怎么解决。感谢

**Comment by KoljaB** [comment]
Looks like something's wrong around the CUDA installation, hard to say what.

Is [CUDA Tookit](https://github.com/KoljaB/RealtimeTTS?tab=readme-ov-file#cuda-installation) installed? Please verify that environment variables CUDA_PATH and CUDA_HOME are set to the correct CUDA installation folder, for example:
```
set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1"
set "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1"
```

Maybe cudart64_12.dll can't be found and needs to be put in a folder that's in PATH env. Maybe just uninstalling flash attn works ("pip3 uninstall flash-attn").

Could also be wrong python version (coqui tts requires [Python >= 3.9, < 3.13](https://github.com/KoljaB/RealtimeTTS?tab=readme-ov-file#requirements-explained)).

If nothing works please try to install in a fresh virtual environment to see if that issue persists.
