### ISSUE TITLE
Error initializing main faster_whisper transcription model: Error opening 'female.wav': System error.

### ISSUE THREAD

**Issue by salahzoubi** [KoljaB/RealtimeTTS#4]
Hi, I just tried using your API on a jupyter notebook with the CoquiTTS engine. It seems like it's expected a female.wav file to be present? Here's the error I'm getting:

```
ERROR:root:Error initializing main faster_whisper transcription model: Error opening 'female.wav': System error.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/RealtimeTTS/engines/coqui_engine.py", line 135, in _synthesize_worker
    gpt_cond_latent, speaker_embedding = get_conditioning_latents(cloning_reference_wav)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/RealtimeTTS/engines/coqui_engine.py", line 95, in get_conditioning_latents
    gpt_cond_latent, speaker_embedding = tts.get_conditioning_latents(audio_path=filename)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 343, in get_conditioning_latents
    audio = load_audio(file_path, load_sr)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 73, in load_audio
    audio, lsr = torchaudio.load(audiopath)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/_backend/utils.py", line 203, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/_backend/soundfile.py", line 26, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/_backend/soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ubuntu/miniconda3/envs/whisper/lib/python3.9/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'female.wav': System error.
Process Process-1:
```

**Comment by KoljaB** [comment]
Hi salahzoubi,

there is no wave file delivered with the project. Coqui TTS computes so called "speaker latents" from the clone source, which I save as a JSON-File ([male.json](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/male.json) and [female.json](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/female.json) for this project). This JSON is always generated for any input cloning wave file, so after starting it once you won't need the wave anymore. I think it is cleaner to only deliver the resulting .json.

So you need to copy the female.json into your jupyter notebook (or just use another .wave file containing your desired voice example to clone).

Hope that helps, just ask me if anything is still unclear.

**Comment by salahzoubi** [comment]
hi @KoljaB, should I just copy this to the local directory I'm running my notebook in, or do I feed this to the CoquiEngine as a dict?

**Comment by KoljaB** [comment]
Just put the female.json into your local notebook directory, where the .ipynb-file is and it should work

**Comment by KoljaB** [comment]
Default voice implemented, so a female.json or any other kind of cloning source is not needed any more with v.0.2.4, will close this
