### ISSUE TITLE
KeyError: 'audio'

### ISSUE THREAD

**Issue by ajeema** [KoljaB/RealtimeTTS#49]
I continue to get this error and have yet to figure out why. Any ideas?

`Exception in thread Thread-2 (play):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/RealtimeTTS/text_to_stream.py", line 231, in play
    self.engine.synthesize(self.char_iter)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/RealtimeTTS/engines/elevenlabs_engine.py", line 121, in synthesize
    self.stream(self.audio_stream)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/RealtimeTTS/engines/elevenlabs_engine.py", line 177, in stream
    for chunk in audio_stream:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/elevenlabs/api/tts.py", line 134, in generate_stream_input
    if data["audio"]:
       ~~~~^^^^^^^^^
KeyError: 'audio'
`

**Comment by KoljaB** [comment]
It's a [known elevenlabs](https://github.com/elevenlabs/elevenlabs-python/issues/136#issuecomment-1901282228) issue.

Try using eleven_monolingual_v1 and eleven_multilingual_v1 models, but not the v2 models, they are not fast enough for realtime streaming. In the elevenlabs thread some other possible reasons are mentioned: missing API key, unended/timed-out input stream, account usage exceeded. Subscription to a elevenlabs paid membership also was mentioned.

**Comment by ajeema** [comment]
I did come across some of those, I will continue to explore. Thank you
