### ISSUE TITLE
Possible invalid elevenlabs version being used

### ISSUE THREAD

**Issue by Gregorein** [KoljaB/RealtimeTTS#57]
I believe `elevenlabs` dependency version need freezing or should be refactored when their engine is not being imported:

I'm getting following error on python 3.12:

```bash
Traceback (most recent call last):
  File "tts.py", line 1, in <module>
    from RealtimeTTS import CoquiEngine, TextToAudioStream
  File ".venv/lib/python3.12/site-packages/RealtimeTTS/__init__.py", line 1, in <module>
    from .text_to_stream import TextToAudioStream
  File ".venv/lib/python3.12/site-packages/RealtimeTTS/text_to_stream.py", line 1, in <module>
    from .engines import BaseEngine
  File ".venv/lib/python3.12/site-packages/RealtimeTTS/engines/__init__.py", line 4, in <module>
    from .elevenlabs_engine import ElevenlabsEngine
  File ".venv/lib/python3.12/site-packages/RealtimeTTS/engines/elevenlabs_engine.py", line 2, in <module>
    from elevenlabs import voices, generate, stream

ImportError: cannot import name 'generate' from 'elevenlabs' (venv path here)
```

**Comment by KoljaB** [comment]
Please upgrade to [latest RealtimeTTS version 0.3.43](https://github.com/KoljaB/RealtimeTTS/releases/tag/v0.3.43), that should have been fixed same day it occurred.

**Comment by Gregorein** [comment]
The issue was on my side, pip somehow wasn't recognizing the latest versions on pypi, so i downgraded the python from 3.12 to 3.10. and pulled directly from your repo.
