### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by datasciritwik** [KoljaB/RealtimeTTS#69]
I have run this
```
from RealtimeTTS import TextToAudioStream, SystemEngine, AzureEngine, ElevenlabsEngine

engine = SystemEngine() # replace with your TTS engine
stream = TextToAudioStream(engine)
stream.feed("Hello world! How are you today?")
stream.play_async()
```

Error
------
Traceback (most recent call last):
  File ".\tts-realtime.py", line 8, in <module>
    import RealtimeTTS
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\RealtimeTTS\__init__.py", line 1, in <module>
    from .text_to_stream import TextToAudioStream
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\RealtimeTTS\text_to_stream.py", line 1, in <module>
    from .engines import BaseEngine
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\RealtimeTTS\engines\__init__.py", line 4, in <module>
    from .elevenlabs_engine import ElevenlabsEngine
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\RealtimeTTS\engines\elevenlabs_engine.py", line 2, in <module>
    from elevenlabs import voices, generate, stream
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\__init__.py", line 3, in <module>
    from .types import (
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\types\__init__.py", line 4, in <module>
    from .add_project_response_model import AddProjectResponseModel
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\types\add_project_response_model.py", line 7, in <module>
    from .project_response import ProjectResponse
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\site-packages\elevenlabs\types\project_response.py", line 15, in <module>
    class ProjectResponse(pydantic.BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 636, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 781, in pydantic.fields.ModelField._create_sub_type
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\12345\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by KoljaB** [comment]
Perhaps not elevenlabs==0.2.27? Currently this lib is not yet adapted to elevenlabs>=1.0.0

**Comment by datasciritwik** [comment]
Solved!! 
Previously, I tried to install it using Python 3.8, and that's why I faced issues.
Thx.
