### ISSUE TITLE
ElevenLabs API change

### ISSUE THREAD

**Issue by jrmann1999** [KoljaB/RealtimeTTS#83]
ElevenLabs has deprecated top level functions:

Exported functions
The SDK no longer exports top level functions generate, clone, and voices. Instead, everything is now directly attached to the client instance.

generate -> client.generate

To that end, when using pip to install the most recent version of RealtimeTTS, it installs the newest elevenlabs which breaks RealtimeTTS:

>>> from RealtimeTTS import SystemEngine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jerem\OneDrive\Documents\TTS\Lib\site-packages\RealtimeTTS\__init__.py", line 1, in <module>
    from .text_to_stream import TextToAudioStream
  File "C:\Users\jerem\OneDrive\Documents\TTS\Lib\site-packages\RealtimeTTS\text_to_stream.py", line 1, in <module>
    from .engines import BaseEngine
  File "C:\Users\jerem\OneDrive\Documents\TTS\Lib\site-packages\RealtimeTTS\engines\__init__.py", line 4, in <module>
    from .elevenlabs_engine import ElevenlabsEngine
  File "C:\Users\jerem\OneDrive\Documents\TTS\Lib\site-packages\RealtimeTTS\engines\elevenlabs_engine.py", line 2, in <module>
    from elevenlabs import voices, generate, stream
ImportError: cannot import name 'generate' from 'elevenlabs' (C:\Users\jerem\OneDrive\Documents\TTS\Lib\site-packages\elevenlabs\__init__.py)
>>>

I'm sure an engine rewrite is needed, but figured I'd raise the issue since it impacts even when not directly importing the ElevenLabs engine.

**Comment by KoljaB** [comment]
Thanks for pointing out. Latest version 0.3.47 should now support new elevenlabs api.

**Comment by jrmann1999** [comment]
Thanks!  I'll test when it hits pip to upgrade.

**Comment by KoljaB** [comment]
Upped version to 0.3.48 (0.3.47 somehow did not update elevenlabs library).
Should be up on pypi now and available with `pip install realtimetts==0.3.48` or `pip install -U realtimetts`.

**Comment by jrmann1999** [comment]
Working Great.
